apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: "7.0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    admin:
      existingSecret: "grafana-admin"
      userKey: admin-user
      passwordKey: admin-password
    persistence:
      enabled: false
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false