apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
data:
    #ENC[AES256_GCM,data:XYvISsaW0DyVFh4yTO8W,iv:2NZ5h3A/l3Lo5pxpsp2cwzXNpiVerWK2zLCnghiSH0M=,tag:GEkMe4/87hC1eIDkAvaYkA==,type:comment]
    admin-user: ENC[AES256_GCM,data:rW7ceQsqPM8=,iv:JI20XyavJS7WLVZG21cKXsCx4wyOnvLNT5+Om49hAhY=,tag:oyG6XFR5nD3XIFlnDNx/Sg==,type:str]
    #ENC[AES256_GCM,data:gTg6DVEJFlwXxo6WG6zk10rjww==,iv:AqJJ3a+JNHmGmfu52+446oPpAnse68tfas1weWmYvZs=,tag:swX7jQ4FVEtdkvvxapAWDg==,type:comment]
    admin-password: ENC[AES256_GCM,data:A0I8giNhzq71yo4x,iv:WL1sXHgl+D9RGqfKgOoLsvbHPsXScQp+GGd9zSRUvRI=,tag:98rd8rj8ISeqlFZGoKeizA==,type:str]
sops:
    age:
        - recipient: age18pzu5h6a7u6v73mren28s9a799lemljpfqa7py0uw76c8yh9zvnsu4eg4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdGoyeEJwdDB6NGxFaWQx
            aVA0RFY4V09GR0NHVEFFaDVWMVlOdm16Z0VJCjVPa1psdStFMnluT1pDd1phR0wy
            MSsvdSs5U1VNUzdGNUhIRlNnY0JXekkKLS0tIHlCTm04OVF2ZkZoZE50aExDTzI0
            eitHZzVYTUREaXJoZklyTXFFbktPYnMKzqvS5PvQr9SmqXkTyqmKCD4f0C5fyNNE
            MnQZrqhHMeZ5rNBvlquAzKNf3l7GfTXuzh6h2RkCWbVyOfWiW5cmsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:50:53Z"
    mac: ENC[AES256_GCM,data:ceMLHGL7CuCM3SBE8V46guqOSnBuljaq27syoymr+HBGt9jO85IKhimqO5UUrAdF8lpiY4gHMt/uXgiOp6hVvmUMIubLZIUmwM8Ps5ECieI54lu33EJ+phKcThhrWGoomQ1KHU5EuPHk+N2mqOXrxlobD0GLvsDLOWwc8kwTr7M=,iv:JpBQDx8kaETT07b6xmfLI73YjTnXqfIVqk4kGSPxhEQ=,tag:bIeOC8jHZh0p1FNIiNAcdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
